name: Python CI
run-name: "CI | ${{ github.event_name }} | ${{ github.ref_name }} | ${{ github.actor }}"

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - name: Show runtime information
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF_NAME: ${{ github.ref_name }}
          HEAD_BRANCH: ${{ github.head_ref }}
          BASE_BRANCH: ${{ github.base_ref }}
          COMMIT_SHA: ${{ github.sha }}
          RUNNER_OS: ${{ runner.os }}
        run: |
          echo "Event: $EVENT_NAME"
          echo "Reference: $REF_NAME"
          echo "PR source: $HEAD_BRANCH"
          echo "PR target: $BASE_BRANCH"
          echo "Commit: $COMMIT_SHA"
          echo "Runner OS: $RUNNER_OS"

      - name: Download repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.29"
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Check code quality
        run: uv run ruff check .

  test:
    name: Run Python tests
    needs: quality
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: "0.11.29"
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install project dependencies
        run: uv sync --locked --dev

      - name: Run tests
        run: uv run pytest -v